---
# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

# Simplified Ceph Cluster for minikube - only verified fields
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
  labels:
    ramendr-demo: "true"
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  
  # Monitor configuration
  mon:
    count: 1
    allowMultiplePerNode: true
  
  # Manager configuration  
  mgr:
    count: 1
    allowMultiplePerNode: true
  
  # Dashboard configuration
  dashboard:
    enabled: true
    ssl: false
    
  # Monitoring disabled
  monitoring:
    enabled: false
    
  # Network configuration
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
        
  # Crash collection
  crashCollector:
    disable: true
    
  # Log collection
  logCollector:
    enabled: false
    
  # Storage configuration - specify loop devices explicitly
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "ramen-dr1"  # Match the actual minikube node name
      devices:
      - name: "/dev/loop0"  # Use the loop device we created for dr1
        config:
          deviceClass: "ssd"
    
  # Disruption management
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
    
  # Health checks
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
