apiVersion: v1
data:
  jws-kubeconfig-ieoq9v: eyJhbGciOiJIUzI1NiIsImtpZCI6Imllb3E5diJ9..dqddFsNx-KabWWGjDRgLVkvEcP6WVL0qAUV9mKz7IVs
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1UQXdOREUwTXpVek9Gb1hEVE0xTVRBd016RTBNelV6T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjFUCitKZGNucUZGZ2MyS1JWNCtKM2pma3hLYkpaVTJsR0J5M2cydytoM3YrblBhdzc0SVdMYXlQMFZ6bkV3L2VJRFcKTWthQWVwTUltZ3VVaUhRR3BUUmczNGxtd1B4N2lXZDAzT1dvWHNTUW5pVjVDZXk2aFo0OXZrZEVMTFpuYkJlUApnQlNLb1VYclZoYW9KSU1kVWhOcmlvRDRTcGFaSllTVkVqVUMzRDFPSUdaM2oyWDFvN3dPTHdJWkoxU2ZPMXNUCkxIRmlMYzg4Mm5tYXBaWUpFMm8vZ1dKR0VjV1VwTXRoc0VVRi9SdmVOUkc5dmFOWnNCN2ttMWhqYnEzcDlkVVYKNmYzQkxPRVlaUTFmTkFmUUxKRTh3aEd2dW9kK1FTb3U3N2hweFRvZjUxRjVlaGNEZzN5dUtnWXozWnNOZ1A5bQpkTUIrSjJTUHRBNWlEVGlOaVpNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTU0NXZUVZU0FDOS83dTMzKzFKQWVUNHlSSStUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFuYldhc01rKwpldWtObzdxOUluWjFJMmExSkhWcjZyRDhYTTJaNWNiU21ST2UxUllDRzRiTHNvUUJDdXl3TVZoM3BSZWRhOE9NCjZxZW1TL241SVg1SldpV016d0Z2dlB5Z2p4K3lERDU0bEJMWjdKTlE3akRnOWdXVGIzMUQ4YU5VQzlYT0lnRUsKUnZ5OTFDVGp1eERjZy9Da0ZPNWRiRGtTUUszOGdyRnFNTnczeGNNSWxnNDVQWm1LZ0tta05PbGpTVUdIeTArSgpIcFpSUHZmZ3puVzFKVS9wbVB4d1NqcGhlM1pNK1VTUW1NOHpNSDA1YWI5dUF2UlRjRDBwUFVXaEx5NzBpUGQ5ClovT0RwZkY4YmtUdjNwcWtOdEd2TjU4UWhLWDd0OHpEU20xM09jRTJIeFo1bWI1YUg2OHAwQ3ArODB5SGVIbGYKZ0VVZUgzQ29CM3JFMGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://control-plane.minikube.internal:8443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-05T14:35:44Z"
  name: cluster-info
  namespace: kube-public
  resourceVersion: "352"
  uid: 6667e0d3-58ee-4ea8-ac34-df520bf8cf5f
