# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
ignore: |
  config/**
  hack/test/*
  examples/**
  demo/**
  Temp/**
rules:
  indentation:
    indent-sequences: consistent
  line-length: disable
  document-start: disable
  truthy:
    check-keys: false
