apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: dr-secondary-placement
  namespace: nginx-test
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: ramen-dr2