---
# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

# DRPlacementControl for nginx-test application
# This tells RamenDR to protect the nginx-test namespace and creates VRGs
# Updated to use Placement (v1beta1) instead of legacy PlacementRule

apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: nginx-test-drpc
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  # Reference to the DRPolicy we created (from setup-dr-policy.sh)
  drPolicyRef:
    name: ramen-dr-policy

  # Reference to Placement (updated from PlacementRule)
  placementRef:
    kind: Placement  # Changed from PlacementRule
    name: dr-primary-placement  # Matches dr-primary-placement.yaml in dr-policy/
    namespace: nginx-test

  # Which cluster should be primary (where app runs initially)
  preferredCluster: ramen-dr1

  # Which cluster to failover to
  failoverCluster: ramen-dr2

  # PVC selector - which PVCs to protect (matches labels in nginx-with-pvc.yaml)
  pvcSelector:
    matchLabels:
      app: nginx-test

  # Action to take (can be 'Relocate' for failover or 'Failover' for permanent switch)
  action: Relocate