apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumegroupreplications.replication.storage.openshift.io
spec:
  group: replication.storage.openshift.io
  names:
    kind: VolumeGroupReplication
    listKind: VolumeGroupReplicationList
    plural: volumegroupreplications
    singular: volumegroupreplication
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true