# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

# Manual VolumeReplicationGroup for Testing S3 Backup
# This demonstrates what RamenDR creates automatically in a full OCM environment

apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: nginx-test-vrg
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  # Reference to our DRPolicy
  drPolicy: ramen-dr-policy
  
  # S3 profiles for metadata storage
  s3Profiles:
  - minio-s3
  
  # PVC selector to protect our nginx PVC
  pvcSelector:
    matchLabels:
      app: nginx-test
  
  # Replication state (primary = active, secondary = standby)
  replicationState: primary
  
  # Volume replication classes (if available)
  volumeReplicationClasses:
  - matchLabels:
      ramendr.openshift.io/replicationID: ramen-volsync
