---
# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

# Test Application with PVC for RamenDR Verification
# This creates a simple nginx application with persistent storage

apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
  labels:
    app.kubernetes.io/name: nginx-test
    ramendr.openshift.io/protected: "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx-test
  labels:
    app: nginx-test
    ramendr.openshift.io/protected: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    # Use default storage class
    # storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html
          # Create test data
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "<h1>RamenDR Test Application</h1>" > /usr/share/nginx/html/index.html
              echo "<p>Deployment time: $(date)</p>" >> /usr/share/nginx/html/index.html
              echo "<p>Hostname: $(hostname)</p>" >> /usr/share/nginx/html/index.html
              echo "<p>Data protected by RamenDR</p>" >> /usr/share/nginx/html/index.html
              nginx -g "daemon off;"
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-test
