apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkfenceclasses.csiaddons.openshift.io
spec:
  group: csiaddons.openshift.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Cluster
  names:
    plural: networkfenceclasses
    singular: networkfenceclass
    kind: NetworkFenceClass