apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumegroupreplications.replication.storage.openshift.io
spec:
  group: replication.storage.openshift.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: volumegroupreplications
    singular: volumegroupreplication
    kind: VolumeGroupReplication